{% set version = "3.0.0" %}

package:
  name: ordered-set
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/o/ordered-set/ordered-set-{{ version }}.tar.gz
  sha256: a34399fe6aa78358aaa00129d67c65b4aa099adfc023731b1d756c85776a89bb

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - pytest-runner
  run:
    - python

test:
  imports:
    - ordered_set

about:
  home: http://github.com/LuminosoInsight/ordered-set
  license: MIT
  license_file: MIT-LICENSE
  summary: 'A MutableSet that remembers its order, so that every entry has an index.'


extra:
  recipe-maintainers:
    - benjwadams
    - ocefpaf
