{% set version = "4.0.2" %}

package:
  name: ordered-set
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/o/ordered-set/ordered-set-{{ version }}.tar.gz
  sha256: ba93b2df055bca202116ec44b9bead3df33ea63a7d5827ff8e16738b97f33a95

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5

test:
  imports:
    - ordered_set
  commands:
    - pip check
  requires:
    - pip


about:
  home: http://github.com/LuminosoInsight/ordered-set
  license: MIT
  license_file: MIT-LICENSE
  summary: A MutableSet that remembers its order, so that every entry has an index.


extra:
  recipe-maintainers:
    - benjwadams
    - ocefpaf
