{% set version = "3.0.1" %}

package:
  name: ordered-set
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/o/ordered-set/ordered-set-{{ version }}.tar.gz
  sha256: 3d6fd7bffbb15f613a9e8a6281bf97c2d67f7bb8677deca8249df2fbdd9cce7b

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - pytest-runner
  run:
    - python

test:
  imports:
    - ordered_set

about:
  home: http://github.com/LuminosoInsight/ordered-set
  license: MIT
  license_file: MIT-LICENSE
  summary: 'A MutableSet that remembers its order, so that every entry has an index.'


extra:
  recipe-maintainers:
    - benjwadams
    - ocefpaf
