{% set version = "3.1.1" %}

package:
  name: ordered-set
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/o/ordered-set/ordered-set-{{ version }}.tar.gz
  sha256: a7bfa858748c73b096e43db14eb23e2bc714a503f990c89fac8fab9b0ee79724

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
    - pytest-runner
  run:
    - python

test:
  imports:
    - ordered_set

about:
  home: http://github.com/LuminosoInsight/ordered-set
  license: MIT
  license_file: MIT-LICENSE
  summary: 'A MutableSet that remembers its order, so that every entry has an index.'


extra:
  recipe-maintainers:
    - benjwadams
    - ocefpaf
