# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Gi3p8jXxWgJe54wdWRjz9AQeI/Fxax3stQa7OnDnDYWhw/b7y1ksOsfBKXxX/Zly3j8dsjwFW1eJeQpioc1762IbXTUDdfZbx701/CO+SXsKlkohDOuoYVKYkdR9zP1f/5RhZ1Qei5KHw/2wL6Yh6CEgYsP4xiQCxZJLvAq6j1+cQGRvktaXeWXUqwHlAyQZNLX0oB22w1V+OY6OB2w1s6Ioai9dS+r9f0pc2dgO8tyhrf4Y9Zhpsb/Oab0fZKtV3oNOeYb14ZaOJZa6TCzs8uOdidmozSQr61dl5FyJDNysUe1GbvDWZOj34vJcFX09E+Q8Ny1zRQ0kvMOPlk6cYgGYlZRZS8EXny4MzgiZ2POjFUc3/2Fmn7B4FCz+NUMmfCQHq4apzrnKUFAwHKT59CwLNEhWsEzRm4Ft3QmHTQ7nRmsVOEpOxFSG6+A6k0MNWg4AfYJ46O8EBlFT/5zHZQn4tMjYXhaZ4L1fL7JiM+rIjAMGVdb3DoZ2ue7oMz/Twji2tBFypIxiJMeR6dKIJzPjwyptQ18OQGMB++r0QvHR/GKn4TTHEjoeiml72arAKlsz2J6/xliqGXp9y69yOnlOy9egYEwRiyF9AEIZJUHc4+2+jjDzugJn5khorZyQL4Sl6iIX7XWGuOgaJnIPBMflcoU/Q1qx/J2BtINUp+k="


before_install:
    - brew remove --force $(brew list)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
