travis:
  secure:
    BINSTAR_TOKEN: PgN2mK0M7msd+GRdsUIrpkKreEtYSVkLVz1hRD/dZWpVFtnmSr8OsohZzyS1v6q08qaDLYgY26bRfoi/YpKfCPT5MipQo1EPqnRE+4+NY229RiVhGQgQiJXg8BiuvVZqC1RTL8pvLHVnLKq4sbkVVISgvqAgvtT8DjX2kGbhpoG0t5LiqVw0nS6EM7O3oxZ1k0Mf67phcwYRwBGxqqbMWqQD3dJP/6sx0npVyokHt3vQwGeN1q7peRR+QRvhtLsG3QrX8XnltZflFOZNzEWT/bCUFXxe6EiPBrUEYB4IwCvMs+63GFGniQjYNf4LPtNFxgPPgDU0e/w1i9dh842jFSrDB0/d8hu6NCvWyssWrNEjilY38LfVX3kRfX4w++jo4rf2fDQz+FabNRzKMF2T3vNIJq4knJ75O3VpngaJN5MoykjY1mJGvXaAANxG2ch08DIdrpkwTc9SdtgoNZ/iUdCQNJq7jSQEy3Mzfd/5DDXV5E2iS9g4tbgsi8tpWaj89rSPc6ACxiGfQgpn0FToWtxsWAE/CHSPRAHMs92yG7Av3pFnNSf8+wtK5a1qQMNAlqBUdF8DtNt8sVVHoVMkXbyG51Er7VSGzCoI198xi+2sx+E6mrhwrg0b3qAsmLLRFwOM4s7jJj3BjYWQ9wffEHX7zs/9FtW9N6zbgLWelSQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
