travis:
  secure:
    BINSTAR_TOKEN: Gi3p8jXxWgJe54wdWRjz9AQeI/Fxax3stQa7OnDnDYWhw/b7y1ksOsfBKXxX/Zly3j8dsjwFW1eJeQpioc1762IbXTUDdfZbx701/CO+SXsKlkohDOuoYVKYkdR9zP1f/5RhZ1Qei5KHw/2wL6Yh6CEgYsP4xiQCxZJLvAq6j1+cQGRvktaXeWXUqwHlAyQZNLX0oB22w1V+OY6OB2w1s6Ioai9dS+r9f0pc2dgO8tyhrf4Y9Zhpsb/Oab0fZKtV3oNOeYb14ZaOJZa6TCzs8uOdidmozSQr61dl5FyJDNysUe1GbvDWZOj34vJcFX09E+Q8Ny1zRQ0kvMOPlk6cYgGYlZRZS8EXny4MzgiZ2POjFUc3/2Fmn7B4FCz+NUMmfCQHq4apzrnKUFAwHKT59CwLNEhWsEzRm4Ft3QmHTQ7nRmsVOEpOxFSG6+A6k0MNWg4AfYJ46O8EBlFT/5zHZQn4tMjYXhaZ4L1fL7JiM+rIjAMGVdb3DoZ2ue7oMz/Twji2tBFypIxiJMeR6dKIJzPjwyptQ18OQGMB++r0QvHR/GKn4TTHEjoeiml72arAKlsz2J6/xliqGXp9y69yOnlOy9egYEwRiyF9AEIZJUHc4+2+jjDzugJn5khorZyQL4Sl6iIX7XWGuOgaJnIPBMflcoU/Q1qx/J2BtINUp+k=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
