travis:
  secure:
    BINSTAR_TOKEN: m15QG4F+zF+Kl37CjF4W355AenvFiYH70vl2QIJoB2fyvsW6nWpAQypYx5KM5oohovlQCcrOd+kDZ15IBUj2BMSn4XHq+53h+iOhkTCyjvK/yZNWDzEozZUEX5noawAxy8M0wUFF2HDGA5432uSmR2YtlYBLtlmvIRSpu4NgGGZmEY1BzHiEWYOBQ2cguOC3+NUUcvV4ktIWYNAxVYQOEG8cwDx1rYKcXRO4aC6/PUMzSSUtsSCT6MApsJuDRiusJIwQjtBQYOVJqWbOFrXYx5UnRLhbIlQgUpsxsCjskXUX9nyOtKzjlckfZIowprWubLS5TqmW+EOX/prQ4YXuDh+Lpm11jXsGH5XmUDtojlRdCbKNBpesdZlOnUGoe+Eugwx4tbS3mXSFDnem7OQiZizFWzppjx3ee0govhHG/VeaqvpudROQtDGlucBPQ9sB3dhVC2b7wjC8mglJzsJ6Lzeow5lLjpJNkgbJr3CB3dq67xJDlbZG5q4CwDTflnuyvPly8prGABdLwOvtBjnCitVSQR/XfX7cdQvIgg5eMAvz38ry7Y0Wu5dmsSEq+Y30XMKx7vLh8vkYyIytwtAxdO1MlDoLOYsJp0XTssxQzbD6w0eoebR7hlr9RbSRNsIkLB/6OEI6FmufasAMRj80JUw/uH3ufIQb7mKeSEHTC98=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
